### PR TITLE
Enhance Paragraph Justification for Improved Readability #4899

### PR DESCRIPTION
**Pull request by P0Saurabh**
donec

### CODE REVIEW

**Comment by P0Saurabh** [comment]
What should I do?

**Comment by bartaz** [comment]
Thanks for your contribution, but I'm not sure if merging all the text here into one paragraph and justifying it is an improvement to be honest.

Screenshot 2023-10-23 at 21 17 05

What are you trying to achieve here @P0Saurabh ?

**Comment by P0Saurabh** [comment]
image!
 

Screenshot 2023-10-24 093640

please use a justified form

**Comment by lyubomir-popov** [comment]
Justifying text makes it harder to read, as it alters the distance between letters. The effect gets worse the narrower the column is. If anything, we would add this as an example of what not to do. However, since we don't often get requests like this, I am not sure it is necessary at this point.

Please refer to Robert Bringhurst's "[The elements of typographic style](https://www.goodreads.com/en/book/show/44735)" for a more thorough explanation why justifying text is not a good idea.

**Comment by P0Saurabh** [comment]
thanks

**Pull request closed without merging**
