### PR TITLE
Remove no-padding-top from hero signpost title

### PR DESCRIPTION
**Pull request by jmuzina**
## Done

Removes `.u-no-padding--top` from the hero signpost titles - this was missed in reviews of the Hero pattern and requested to be fixed [here](https://chat.canonical.com/canonical/pl/1bda8imr5bymbde47unn8hjmoe).

## QA

- Open [signpost hero demo](https://vanilla-framework-5341.demos.haus/docs/examples/patterns/hero/hero-signpost-full-width-image)
- Verify that the `.u-no-padding--top` has been removed from the title text

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [x] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [ ] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix release (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [ ] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical/vanilla-framework/blob/main/releases.yml).

## Screenshots

image

### CODE REVIEW

**Comment by jmuzina** [comment]
Design has already +1'd this as it was originally a drive-by of #5275

**Comment by bartaz** [comment]
Looks good codewise, but is this a correct image for the example then? 
With padding the top of the heading, and no spacing on top of image they look quite misaligned.

So, should there be some treatment to this image then, so they align better?

image

@lyubomir-popov any thoughts?

**Comment by lyubomir-popov** [comment]
pls use this logo https://assets.ubuntu.com/v1/fe20126d-RISC-V-logo.svg

preview:
image

**Comment by jmuzina** [comment]
Image updated @lyubomir-popov

**Comment by bartaz** [comment]
@juanruitina should this be updated? https://vanilla-framework-5341.demos.haus/docs/examples/patterns/hero/hero-signpost-full-width-image

**Comment by jmuzina** [comment]
@bartaz Yes I forgot about that one, updating it

**Review by bartaz — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
