### PR TITLE
Add left & right chevron icon variants

### LINKED ISSUE #5066: Add left and right chevrons to vanilla icon set
A component in Vanilla needs to be flexible enough that it can be used across a wide range of scenarios and shouldn't be constrained to a specific number of applications.

## Visual

Screenshot 2024-04-24 at 4 29 14 PM

## Context

at the moment we're using rotated up and down buttons. It's being used across multiple products

## State

The same states as other vanilla. icons

## Progressive enhancement

since it's an icon it works across all screens

### PR DESCRIPTION
**Pull request by jmuzina**
## Done

Adds left & right versions of the chevron icon. These are available as `p-icon--chevron-left` and `p-icon--chevron-right`, respectively.

Fixes #5066, [WD-11767](https://warthogs.atlassian.net/browse/WD-11767)

## QA

- Open [icons page](https://vanilla-framework-5093.demos.haus/docs/patterns/icons) and verify that left and right chevrons are displayed properly.
- Open standalone icons examples that include the chevron and verify the left and right chevrons are displayed properly.
    - https://vanilla-framework-5093.demos.haus/docs/examples/patterns/icons/icons-dark-deprecated
    - https://vanilla-framework-5093.demos.haus/docs/examples/patterns/icons/icons-dark
    - https://vanilla-framework-5093.demos.haus/docs/examples/patterns/icons/icons-light
- Review [release notes](https://vanilla-framework-5093.demos.haus/docs/whats-new) for v4.12.0

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [x] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [x] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [x] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical/vanilla-framework/blob/main/releases.yml).

## Screenshots
image
image
image
image

[WD-11767]: https://warthogs.atlassian.net/browse/WD-11767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by bartaz** [comment]
@lyubomir-popov is this OK to have the same chevron SVG rotated for different orientations, or would we need specific SVG for those for any reason (like slightly different positioning/scaling)?

**Comment by lyubomir-popov** [comment]
> @lyubomir-popov is this OK to have the same chevron SVG rotated for different orientations, or would we need specific SVG for those for any reason (like slightly different positioning/scaling)?

it is ok - it is vertically symmetrical. Can we switch to vertical-align-middle for icons next to paragraph sized text? Works better than the arcane calculation I put in there a long time ago:
image

**Comment by bartaz** [comment]
OK, this could be done as a quick drive-by I guess, seems to be defined here:

https://github.com/canonical/vanilla-framework/blob/b1d651365b0714586e6ea14349dea763819c256e/scss/_base_placeholders.scss#L225

Although, as this would affect all icons by default, I wonder if we want to do this straight there, or limit that to icons inside paragraphs?

I guess we would need to try and see in Percy what it affects.

**Comment by jmuzina** [comment]
> Can we switch to vertical-align-middle for icons next to paragraph sized text? Works better than the arcane calculation I put in there a long time ago

> OK, this could be done as a quick drive-by I guess, seems to be defined here:
> 
> https://github.com/canonical/vanilla-framework/blob/b1d651365b0714586e6ea14349dea763819c256e/scss/_base_placeholders.scss#L225
> 
> Although, as this would affect all icons by default, I wonder if we want to do this straight there, or limit that to icons inside paragraphs?
> 
> I guess we would need to try and see in Percy what it affects.

This more straightforward approach causes some suboptimal alignment changes: see [Percy build](https://percy.io/bb49709b/vanilla-framework/builds/34477947/changed/1885511784?browser=chrome&browser_ids=56&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=375&widths=375%2C1280).

Changing that alignment (only in adjacent-paragraph cases) may require doing something like this, assuming the paragraph text and the `<i>` are both inside a `<p>` element
```scss
p > i[class^='p-icon--'] { 
    vertical-align: middle;
}
```

We'd also need to find a way to avoid applying the default `vertical-align` (the "arcane calculation" referred to by Lyubo) to icons next to paragraph text. Maybe this should be tackled as a separate issue?

**Comment by bartaz** [comment]
> This more straightforward approach causes some suboptimal alignment changes: see [Percy build](https://percy.io/bb49709b/vanilla-framework/builds/34477947/changed/1885511784?browser=chrome&browser_ids=56&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=375&widths=375%2C1280).
> 

That's what I was worried about. Let's drop it from this PR as it unnecessarily affects it. We can create a separate issue about vertical alignment and properly address it there, ouside of context of adding new icon.

Sorry for confusion.

**Comment by jmuzina** [comment]
> > This more straightforward approach causes some suboptimal alignment changes: see [Percy build](https://percy.io/bb49709b/vanilla-framework/builds/34477947/changed/1885511784?browser=chrome&browser_ids=56&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=375&widths=375%2C1280).
> 
> That's what I was worried about. Let's drop it from this PR as it unnecessarily affects it. We can create a separate issue about vertical alignment and properly address it there, ouside of context of adding new icon.
> 
> Sorry for confusion.

No worries! Made an issue #5103 for that alignment change.

**Comment by jmuzina** [comment]
With those alignment changes removed, [Percy build](https://percy.io/bb49709b/vanilla-framework/builds/34479882/changed/1885638729?browser=chrome&browser_ids=56&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280) has no unexpected diffs. Only change is the addition of the two new chevron icons to the icons examples.

**Review by pastelcyborg — APPROVED** [review]

**Review by bartaz — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
