### PR TITLE
Add design guidelines from discourse to Vanilla docs markdown [WD-7623]

### PR DESCRIPTION
**Pull request by aaryanporwal**
## Done

Migrated corresponding design guidelines into a new tab besides implementation and accessibility tab.

Source of the docs: https://discourse.ubuntu.com/c/design-system/98

## QA

- Open [demo](https://vanilla-framework-4927.demos.haus/)
- Review new design guidelines pages added for some components:
  - https://vanilla-framework-4927.demos.haus/docs/patterns/badge/design-guidelines
  - https://vanilla-framework-4927.demos.haus/docs/patterns/buttons/design-guidelines
  - https://vanilla-framework-4927.demos.haus/docs/patterns/chip/design-guidelines
  - https://vanilla-framework-4927.demos.haus/docs/patterns/contextual-menu/design-guidelines
  - https://vanilla-framework-4927.demos.haus/docs/patterns/matrix/design-guidelines
  - https://vanilla-framework-4927.demos.haus/docs/patterns/segmented-control/design-guidelines
  - https://vanilla-framework-4927.demos.haus/docs/patterns/slider/design-guidelines
  - https://vanilla-framework-4927.demos.haus/docs/patterns/switch/design-guidelines

### CODE REVIEW

**Review by bartaz — CHANGES_REQUESTED** [review]

**Comment by bartaz** [comment]
As discussed on Design System Working Group meeting today, the status of design documentation is currently being discussed and the final shape of it is yet to be defined. Therefore we don't want to publish these docs at this time, as they don't reflect what the spec should look like.

I don't want to be throwing away this piece of work as a whole, because while content may not be final, the code changes to make design guidelines show as a new tab are valid and needed. So I think we can drop the markdown content (and the relevant design guidelines config from the yaml file), but keep any other changes. So the new pages can be easily added once needed.

**Comment by bartaz** [comment]
As per discussion in roadmap review meeting, we want to include the existing documentation as is and improve on top of that if needed later.

I'm cleaning up this PR and preparing it for review.

**Comment by danielmutis** [comment]
We need to figure out how to make images better and consistent in terms of size, but for now this is good enough.

**Review by bartaz — APPROVED** [review]
LGTM.

Thanks @aaryanporwal for the initial work on this, it's good to see it go through finally.

**Comment by aaryanporwal** [comment]
Thanks for taking it forward @bartaz.

**Pull request merged**
