### PR TITLE
feat: Publish & Document Jinja Macros

### PR DESCRIPTION
**Pull request by jmuzina**
## Done

Feature branch PR for publishing & documenting Jinja macros

- [x] #5325 
- [x] #5329 
- [x] #5330 
- [x] #5321 
- [x] #5351 

## QA

- See QA instructions on the above PRs if you want to re-QA the feature PR.

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [x] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [x] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix release (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [x] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical/vanilla-framework/blob/main/releases.yml).

[WD-14523]: https://warthogs.atlassian.net/browse/WD-14523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by bartaz** [comment]
Looks good overall.

One downside is that the start of the page is very table-heavy, full of props you need to parse (before you even see what the pattern actually looks like).

image

I'd personally suggest moving the "Jinja Macro" section to the bottom of the page. I know we want devs to have access to this spec, but to me it seems like having the examples first would give a better overview of the component. They are gonna copy the snippet in 90% of cases anyway. Then, if they want to have a look at the reference, they can find it on the page.

Thoughts?

**Comment by jmuzina** [comment]
> One downside is that the start of the page is very table-heavy, full of props you need to parse (before you even see what the pattern actually looks like). I'd personally suggest moving the "Jinja Macro" section to the bottom of the page. I know we want devs to have access to this spec, but to me it seems like having the examples first would give a better overview of the component. They are gonna copy the snippet in 90% of cases anyway. Then, if they want to have a look at the reference, they can find it on the page. Thoughts?

@bartaz Good point. I've moved it to just above the "import" section as I feel it might be a bit disjointed to read examples -> import instructions -> Jinja API docs

We could also move the Jinja API docs to their own tab / sub-page, any thoughts on putting it at bottom of page vs on a separate sub-page? @bartaz @pastelcyborg @advl

**Comment by apollo13** [comment]
Hi, this looks interesting. The slot checking in the macro calling is a bit ugly imo -- the following jinja issue has an alternative that is nicer I think: https://github.com/pallets/jinja/issues/482#issuecomment-431331117  

This would kinda look like this:
```
{% macro vf_hero(
  title_text,
  subtitle_text='',
  layout="fallback",
  is_split_on_medium=false
) -%}
  {% set has_subtitle = subtitle|trim|length > 0 %}
  {% set has_subtitle = subtitle_text|trim|length > 0 %}
  {% set description_content = caller(description=True) if 'description' in caller.arguments else '' %}
  {% set cta_content = caller(cta=True) if 'cta' in caller.arguments else '' %}
```

(see the last lines) and then used in call like this:
```
{% call(description, cta) vf_hero(…) %}
{% if description %}
…
{% else if cta %}
…
{% endif %}
{% endif %}
```

Personally I think this is more readable.

**Review by bartaz — DISMISSED** [review]
LGTM

**Comment by jmuzina** [comment]
> Hi, this looks interesting. The slot checking in the macro calling is a bit ugly imo -- the following jinja issue has an alternative that is nicer I think: [pallets/jinja#482 (comment)](https://github.com/pallets/jinja/issues/482#issuecomment-431331117)

Hi @apollo13 , thanks for your feedback! We've discussed it as a team and decided to stick with the current approach, at least for now - we've established this style as a team standard for this opening round of macros, but will keep it in mind for the future. It's nice to have some feedback from someone who is so familiar with these!

**Comment by apollo13** [comment]
Hi Julie, ok fine with me. The good thing is that if you decide to change it in the future you can support both syntaxes in parallel during a deprecation period. So it is not an end-of-world type decision.

**Pull request merged**
