### PR TITLE
Quote Wrapper Pattern

### PR DESCRIPTION
**Pull request by jmuzina**
## Done

Adds quote wrapper pattern per [Figma](https://www.figma.com/design/Hll6ZRvHyTTGBZZSoRd8ei/Higher-order-components-(HOCs)?node-id=781-188&m=dev)

Fixes [WD-12811](https://warthogs.atlassian.net/browse/WD-12811)

## QA

- [Default](https://vanilla-framework-5204.demos.haus/docs/examples/patterns/quote-wrapper/default)
- [H4](https://vanilla-framework-5204.demos.haus/docs/examples/patterns/quote-wrapper/h4)
- [H2](https://vanilla-framework-5204.demos.haus/docs/examples/patterns/quote-wrapper/h2)

### Check if PR is ready for release

If this PR contains Vanilla SCSS code changes, it should contain the following changes to make sure it's ready for the release:

- [ ] PR should have one of the following labels to automatically categorise it in release notes:
  - `Feature 🎁`, `Breaking Change 💣`, `Bug 🐛`, `Documentation 📝`, `Maintenance 🔨`.
- [ ] Vanilla version in `package.json` should be updated relative to the [most recent release](https://github.com/canonical/vanilla-framework/releases/latest), following semver convention:
  - if CSS class names are not changed it can be bugfix relesase (x.x.**X**)
  - if CSS class names are changed/added/removed it should be minor version (x.**X**.0)
  - see the [wiki for more details](https://github.com/canonical/vanilla-framework/wiki/Release-process#pre-release-tasks)
- [ ] Any changes to component class names (new patterns, variants, removed or added features) should be listed on the [what's new page](https://github.com/canonical/vanilla-framework/blob/main/releases.yml).

## Screenshots

image

[WD-12811]: https://warthogs.atlassian.net/browse/WD-12811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jmuzina** [comment]
Will adjust the top padding on the quote citation tomorrow per [comment](https://www.figma.com/design/Hll6ZRvHyTTGBZZSoRd8ei?node-id=958-1342&m=dev#858892667) from @lyubomir-popov

**Comment by jmuzina** [comment]
Blocked pending merge of #5196

**Comment by jmuzina** [comment]
This is on hold until completion of Hero HOC - we're already working on two HOCs, three is pushing it :)

Leaving a placeholder quote wrapper macro here as a reminder for myself to implement this with a macro when I can pick this up again

**Comment by bartaz** [comment]
There were some changes to this pattern according to Lyubo, not fully speced out yet. So need to put this one on hold.

@jmuzina Now that we have a new approach to building and documenting patterns, I'll let you decide if you think it's worth keeping this PR and updating it later, or just closing it and starting fresh when the pattern is ready to be worked on.

**Comment by jmuzina** [comment]
> There were some changes to this pattern according to Lyubo, not fully speced out yet. So need to put this one on hold.
> 
> @jmuzina Now that we have a new approach to building and documenting patterns, I'll let you decide if you think it's worth keeping this PR and updating it later, or just closing it and starting fresh when the pattern is ready to be worked on.

I can close the PR for housekeeping reasons and pick this back up fresh when it's specced out more

**Pull request closed without merging**
